Onboarding extension version merge
robofit/arcor2_areditor pull request #240
Opened 2022-05-30 17:05 UTC by michalmikus

Version with onboarding extension containing interactive walktrough throughout core functionalities of AREditor.

2022-05-31 07:23 UTC, ZdenekM requested changes
Thanks for the PR! Just a few comments from me, @Kapim will also take a look later this week. There are some typos and many missing articles (a, the) - could you please run texts through Grammarly?

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughHandler.cs
> +public class WalktroughHandler : MonoBehaviour {
Use `OnValidate()` to check that all required GameObjects, etc. are set (not `null`). I think it is a good approach to prevent problems :)

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +    public List<GameObject> Buttons;
Again, I would suggest using `OnValidate` - just to simply check whether it is set.

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            Tip = "Moving pricniples are the same throughout AREditor.",
typo

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            PrimaryText = "When you aim at one of the arrows, you can move or rotate the object, by using slider on the right.\n",
Why is there `\n`?

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +        // lepsie popisat slajder s ktorym sa hybe a co treba urobit pri tom zarovnani
Please, convert comments to English and add `TODO: ` in case of tasks. Or create issues, or remove them :)

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            PrimaryText = "Awesome! \n Home button contains save funcion, settings and exit scene button.",
funcion

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            Tip = "Object have to be whitin reach of the robotic arm.",
whitin

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            PrimaryText = "Cool! \n ADD button contains creation tools for: ACTION (YELLOW ARROW), connetion and ACTION POINT (BALL).",
connetion

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            PrimaryText = "Aim the crosshair on copied move action and press highlighted button.\n",
Should `\n` be there?

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/Assets/TABLET/Scripts/GUI/WalktroughManager.cs
> +            PrimaryText = "All actions near crosshair are shown in left panel. ",
Space after the dot.

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/UserSettings/Search.settings
> +{}
The same here.

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/UserSettings/EditorUserSettings.asset
> +%YAML 1.1
This file probably does not belong to git (nothing in UserSettings).

2022-05-31 07:23 UTC, ZdenekM commented on arcor2_AREditor/UserSettings/Layouts/default-2021.dwlt
> +%YAML 1.1
The same here.

2022-05-31 07:24 UTC, ZdenekM commented
@michalmikus Also, please merge commits into one. Thanks!

2022-07-07 07:40 UTC, Kapim commented
A few comments were added, please, take a look at them, otherwise, it looks OK for me in general.

2022-07-08 06:05 UTC, Kapim requested changes
Use the Base.Singleton (see GameManager) and take a look at the Order property

2023-06-21 09:28 UTC, closed without merging